### ISSUE TITLE
Error in playlist date

### ISSUE THREAD

**Issue by lucile-sticky** [ogamiitto/barde#10]
There is an error in this playlist date:
![capture du 2017-03-07 10 44 27](https://cloud.githubusercontent.com/assets/8859752/23650632/170cf5b4-0323-11e7-8cf3-bbd073b5d605.png)

Should be : 01 janvier 2017

**Comment by david-sticky** [comment]
Good catch, and very strange : the date is correct in the DB and this is the only one with the problem.

**Comment by ogamiitto** [comment]
Fixed it by changing application locales!
