### ISSUE TITLE
Skip disliked songs

### ISSUE THREAD

**Issue by lucile-sticky** [ogamiitto/barde#12]
# Proposition
When a playlist is played, skip all disliked songs. With this, if the user want to listen again a playlist, it will avoid to her/him to manually skip songs s.he doesn't like.

**Comment by ogamiitto** [comment]
But what about users who change their mind, or simply those who want to listen the songs they disliked ?
I dislike JuL but I like to listen to ;)

**Comment by lucile-sticky** [comment]
Add a boolean in the profile to skip/do not skip disliked songs ? :D

**Comment by ogamiitto** [comment]
Available on prod, it does not apply on auto-generated playlists (top, random and worst)
