### ISSUE TITLE
Date for the playlists release 

### ISSUE THREAD

**Issue by lucile-sticky** [ogamiitto/barde#5]
## Proposition
In My account > Songs submitted, you could add to the info the month of release for the playlist.

### Actual
![capture du 2016-11-02 12 24 21](https://cloud.githubusercontent.com/assets/8859752/19927189/e819f4f0-a0f8-11e6-9184-434d434f11d2.png)

### Suggested
![capture du 2016-11-02 12 24 212](https://cloud.githubusercontent.com/assets/8859752/19927192/ec0af67c-a0f8-11e6-81e4-b26c9633008c.png)

**Comment by ogamiitto** [comment]
Done ^^
