### ISSUE TITLE
Songs title size

### ISSUE THREAD

**Issue by lucile-sticky** [ogamiitto/barde#7]
## Problem
I want to submit a song with a long title: 
```When I Was Young I Once Met This Beautiful Girl By A Lake```
But when I try to fil the form, I can only write:
```When I Was Young I Once Met This Beautiful Gi```

## Question
What can I do? Is that possible for you to update the max size of songs title?

**Comment by david-sticky** [comment]
More than a maxlength this is a limit in the database. The length will be raised.

**Comment by ogamiitto** [comment]
Should work now, can you retry ?

**Comment by lucile-sticky** [comment]
Ça marche, merci !
